<style>
    .carregando {
        display: none;
        position: fixed;
        left: 50%;
        top: 50%;
        -webkit-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
        text-align: center;
        font-size: 16px;
        font-weight: bold;
        background-color: white;
        height: 200px;
        width: 200px;
    }
</style>
<div class="page-head"><h2>Filtrar Vários Tipos Questões Aleatórias para a Prova</h2> </br>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
                <?php
                $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar-varias-questoes-aleatorias')));
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('data-role', 'form');
                $form->prepare();
                echo $this->form()->openTag($form);

                $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($dadosProva->getId()));
                echo $this->formHidden($form->get('id'));

                ?>
                <div class="form-group">
                    <div class="col-md-6">-
                        <?= $this->formRow($form->get('id_classificacao_semestre')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="col-md-6">-
                        <?= $this->formRow($form->get('id_fonte_questao')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">-
                        <?= $this->formRow($form->get('id_materia')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="col-md-4">-
                        <?= $this->formRow($form->get('id_assunto_materia')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="col-md-4">-
                        <?= $this->formRow($form->get('id_nivel_dificuldade')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6">-
                        <?= $this->formRow($form->get('id_tipo_questao')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="col-md-6">-
                        <?= $this->formRow($form->get('nr_questoes')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <a id="adicionar" class="btn btn-default" href="#" title="Adicionar Filtro">Adicionar Filtro</a>
                    </div>
                </div>

                <div class="row" id="detalhesfiltros-pagination"></div>
                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">Relacionar Todas</button>
                        <a href="<?= $this->url('navegacao', ['controller' => $controller, 'action'=>'cadastro-questao', 'id'=> Estrutura\Helpers\Cript::enc($dadosProva->getId()) ]) ?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<div class="carregando"><p><img src="/assets/img/carregando1.gif"><p></div>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        $('.carregando').hide();

        $("#dt_aplicacao_prova").datepicker(
            {dateFormat: 'dd/mm/yy'}
        );

        //Função que faz a listagem ser paginada.
        function carregarGridPaginadaAjax(){
            $.ajax({
                type: "post",
                dataType: "text",
                cache: false,
                url: '/prova-prova/detalhes-filtros-pagination',
                async: true,
                data: { id_prova : <?=$dadosProva->getId()?>},
                beforeSend: function () {
                    $('#detalhesfiltros-pagination').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                    );
                },
                success: function (data) {
                    $('#detalhesfiltros-pagination').html(data);
                }
            });
        }
        carregarGridPaginadaAjax(); //Chama a Paginação da listagem

        /*Função Ajax que adiciona os encontros ao Banco de dados*/
        $('#adicionar').click(function() {
            //TODO: Adicionar filtro de preenchimento dos filtros das questoes
            var dados = $('#variasquestaoprovaaleatoriaform').serialize();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '/prova-prova/gravar-adicionar-varias-questoes-aleatorias',
                async: true,
                data: dados,
                success: function(response) {
                    $("#id_materia").val("");
                    if(response.sucesso == true){
                        carregarGridPaginadaAjax();
                    }
                }
            });
            return false;
        });

        $('#id_classificacao_semestre').change(function(){
            if( $(this).val() ) {
                $('#id_materia').hide();
                //$('.carregando').show();
                $.ajax({
                    type: 'POST',
                    dataType: 'json',
                    url: '/prova-prova/carregar-combo-materias-ajax',
                    async: true,
                    data: {
                            id_classificacao_semestre: $(this).val(),
                            id_prova : <?=$dadosProva->getId()?>
                    },
                    success: function(response) {
                        if(response.sucesso == true){
                            var options = '<option value=""> Selecione...</option>';
                            $.each(response.ar_materias, function(i, item) {
                                options += '<option value="' + response.ar_materias[i].id + '">' + response.ar_materias[i].descricao + '</option>';
                            });
                            $('#id_materia').html(options).show();
                            //$('.carregando').hide();
                        } else{
                            $('#id_materia').html('<option value="">-- Erro ao carregar matérias --</option>');
                        }
                    }
                });
            } else {
                $('#id_materia').html('<option value="">-- Escolha uma Classificação --</option>');
            }
        });

        $('#id_materia').change(function(){
            if( $(this).val() ) {
                $('#id_assunto_materia').hide();
                //$('.carregando').show();
                $.ajax({
                    type: 'POST',
                    dataType: 'json',
                    url: '/prova-prova/carregar-combo-assunto-materia-ajax',
                    async: true,
                    data: {
                        id_materia: $(this).val(),
                        id_prova : <?=$dadosProva->getId()?>
                    },
                    success: function(response) {
                        if(response.sucesso == true){
                            var options = '<option value=""> Selecione...</option>';
                            $.each(response.ar_assunto_materia, function(i, item) {
                                options += '<option value="' + response.ar_assunto_materia[i].id + '">' + response.ar_assunto_materia[i].descricao + '</option>';
                            });
                            $('#id_assunto_materia').html(options).show();
                            //$('.carregando').hide();
                        } else{
                            $('#id_assunto_materia').html('<option value="">-- Erro ao carregar Assuntos --</option>');
                        }
                    }
                });
            } else {
                $('#id_assunto_materia').html('<option value="">-- Escolha uma Matéria --</option>');
            }
        });

    });
</script>