<div class="page-head"><h2>Filtrar Questões Aleatórias para a Prova</h2> </br>
</div>

<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
                <?php
                $form->setAttribute('action', $this->url('navegacao', array('controller' => 'questoes_prova-questoesprova', 'action' => 'adicionar-questao-prova-aleatoria')));
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('data-role', 'form');
                $form->prepare();
                echo $this->form()->openTag($form);

                $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($dadosProva->getId()));
                echo $this->formHidden($form->get('id'));

                #O Tipo 1 e a questao de multipla eescolha
                $form->get('id_tipo_questao')->setValue(1);
                echo $this->formHidden($form->get('id_tipo_questao'));
                ?>
                <div class="form-group">
                    <div class="col-md-6">-
                        <?= $this->formRow($form->get('id_fonte_questao')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="col-md-6">-
                        <?= $this->formRow($form->get('id_nivel_dificuldade')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">-
                        <?= $this->formRow($form->get('id_classificacao_semestre')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="col-md-4">-
                        <?= $this->formRow($form->get('id_materia')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="col-md-4">-
                        <?= $this->formRow($form->get('id_assunto_materia')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">-
                        <?= $this->formRow($form->get('nr_questoes')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">Adicionar</button>
                        <a href="<?= $this->url('navegacao', ['controller' => $controller, 'action' => 'cadastro-questao', 'id' => Estrutura\Helpers\Cript::enc($dadosProva->getId())]) ?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<div class="carregando"><p><img src="/assets/img/carregando1.gif"><p></div>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        $('.carregando').hide();

        $("#dt_aplicacao_prova").datepicker(
                {dateFormat: 'dd/mm/yy'}
        );

        $('#id_classificacao_semestre').change(function () {
            if ($(this).val()) {
                $('#id_materia').hide();
                $('.carregando').show();
                $.ajax({
                    type: 'POST',
                    dataType: 'json',
                    url: '/prova-prova/carregar-combo-materias-ajax',
                    async: true,
                    data: {
                        id_classificacao_semestre: $(this).val(),
                        id_prova: <?= $dadosProva->getId() ?>
                    },
                    success: function (response) {
                        if (response.sucesso == true) {
                            var options = '<option value=""> Selecione...</option>';
                            $.each(response.ar_materias, function (i, item) {
                                options += '<option value="' + response.ar_materias[i].id + '">' + response.ar_materias[i].descricao + '</option>';
                            });
                            $('#id_materia').html(options).show();
                            $('#id_assunto_materia').html('<option value="">-- Escolha uma Matéria --</option>');
                            $('.carregando').hide();
                        } else {
                            $('#id_materia').html('<option value="">-- Erro ao carregar matérias --</option>');
                        }
                    }
                });
            } else {
                $('#id_materia').html('<option value="">-- Escolha uma Classificação --</option>');
                $('#id_assunto_materia').html('<option value="">-- Escolha uma Matéria --</option>');
            }
        });

        $('#id_materia').change(function () {
            if ($(this).val()) {
                $('#id_assunto_materia').hide();
                $('.carregando').show();
                $.ajax({
                    type: 'POST',
                    dataType: 'json',
                    url: '/prova-prova/carregar-combo-assunto-materia-ajax',
                    async: true,
                    data: {
                        id_materia: $(this).val(),
                        id_prova: <?= $dadosProva->getId() ?>
                    },
                    success: function (response) {
                        if (response.sucesso == true) {
                            var options = '<option value=""> Selecione...</option>';
                            $.each(response.ar_assunto_materia, function (i, item) {
                                options += '<option value="' + response.ar_assunto_materia[i].id + '">' + response.ar_assunto_materia[i].descricao + '</option>';
                            });
                            $('#id_assunto_materia').html(options).show();
                            $('.carregando').hide();
                        } else {
                            $('#id_assunto_materia').html('<option value="">-- Erro ao carregar Assuntos --</option>');
                        }
                    }
                });
            } else {
                $('#id_assunto_materia').html('<option value="">-- Escolha uma Matéria --</option>');
            }
        });

    });
</script>