<div class="page-head"><h2>Provas</h2> </br>
</div>
<div class="block-flat">
    <div class="content">
        <?php
        $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'imprimir-prova-pdf', 'id' => Estrutura\Helpers\Cript::enc($dadosProva->getId()))));
        $form->setAttribute('class', 'form-horizontal');
        $form->setAttribute('data-role', 'form');
        $form->prepare();
        echo $this->form()->openTag($form);
        $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
        echo $this->formHidden($form->get('id'));
        #xd($dadosProva);
        ?>
        <div class="bs-callout bs-callout-primary">
            <div class="row">
                <div class="col-md-12">
                    <h4><b>Registro nº:</b> <?= $dadosProva->getId() ?></h4>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <b>Data da
                        Aplicaçao:</b> <?= Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($dadosProva->getDtAplicacaoProva()) ?>
                </div>
                <div class="col-md-7">
                    <b>Nome da Prova:</b> <?= $dadosProva->getNmProva() ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <b>Resumo:</b> <?= $dadosProva->getDsProva() ?>
                </div>
            </div>
        </div>
        <div style="text-align: center" class="row form-group">
            <div class="well col-md-12">
                <div class="col-md-6">
                    <a href="<?= $this->url('navegacao', ['controller' => $controller, 'action' => 'adicionar-questao-manual', 'id' => Estrutura\Helpers\Cript::enc($dadosProva->getId())]) ?>"
                       class="btn btn-primary">Adicionar Questão Manual</a>
                </div>

                <div class="col-md-6">
                    <a href="<?= $this->url('navegacao', ['controller' => $controller, 'action' => 'adicionar-questao-aleatoria', 'id' => Estrutura\Helpers\Cript::enc($dadosProva->getId())]) ?>"
                       class="btn btn-primary">Adicionar Questão Aleatória</a>
                </div>

<!--                <div class="col-md-4">-->
<!--                    <a href="$this->url('navegacao', ['controller' => $controller, 'action' => 'adicionar-varias-questoes-aleatorias', 'id' => Estrutura\Helpers\Cript::enc($dadosProva->getId())]) ?>"-->
<!--                       class="btn btn-primary">Adicionar Várias Questões</a>-->
<!--                </div>-->
            </div>
        </div>

        <!-- Monta a prova para exibicao       -->
        <div style="text-align: center" class="row form-group">
            <div class="well col-md-12">
                <?php
                $nrQuestoes = count($arQuestoesProva);
                if ($nrQuestoes == 0) {
                    $ocultarBotoes = true;
                    ?>
                    <div style="text-align: center" class="row form-group">
                        <div class="col-md-12">
                            <?php
                            echo "<h2> Não existem questões adicionadas a esta avaliação</h2>";
                            ?>
                        </div>
                    </div>
                    <?php
                } else {
                    $ocultarBotoes = false;
                    echo "<h2> Questões da Prova </h2>";
                    ?>
                    <div style="text-align: left" class="row form-group">
                        <div class="col-md-12">
                            <?php
                            $questaoService = new \Questao\Service\QuestaoService();
                            $alternativaquestaoService = new \AlternativaQuestao\Service\AlternativaQuestaoService();
                            $i = 1;
                            foreach ($arQuestoesProva as $key => $item) {
                                $arQuestao = $questaoService->buscar($item['id_questao'])->toArray();
                                echo "<div id='quest_{$item['id_questao']}'>";
                                echo "<span> <button id='btnremoverquest_{$item['id_questao']}' name='btnremoverquest' value='{$item['id_questao']}' class='btn btn-default'> {$i} - Remover </button></span>";
                                echo "<span> <a href='" . $this->url('rota_questao_via_prova', ['controller' => 'questao-questao', 'action'=> 'cadastro-via-prova', 'id' => Estrutura\Helpers\Cript::enc($item['id_questao']), 'id_prova' => Estrutura\Helpers\Cript::enc($dadosProva->getId())]) . "' class='btn btn-default'> {$i} - Corrigir</a></span>";
                                echo "<h3>" . $i++ . " - " . $arQuestao['nm_titulo_questao'] . " [Identificador: {$item['id_questao']}]" . "</h3>";
                                echo "<h4>" . $arQuestao['tx_enunciado'] . "</h4>";
                                $arAlternativaQuestao = $alternativaquestaoService->fetchAllById(['id_questao' => $item['id_questao']]);
                                $j = 'a';
                                foreach ($arAlternativaQuestao as $key => $alternativa) {

                                    $tx_alternativa_questao = isset($alternativa['tx_alternativa_questao']) && $alternativa['tx_alternativa_questao'] ? $alternativa['tx_alternativa_questao'] : "";
                                    $tx_alternativa_questao = strip_tags($tx_alternativa_questao); #Remove qualquer tag HTML


                                    $tx_justificativa = isset($alternativa['tx_justificativa']) && $alternativa['tx_justificativa'] ? $alternativa['tx_justificativa'] : "";
                                    $tx_justificativa = strip_tags($tx_justificativa);#Remove qualquer tag HTML

                                    if ($alternativa['cs_correta'] == 'C') {

                                        echo "<h4 style='background-color: #4cae4c'>" . $j++ . ") - (_x_) " . $tx_alternativa_questao . "</h4>";
                                        echo "<h5 style='background-color: #4cae4c'>Justificativa: " . $tx_justificativa . "</h5>";
                                    } else {

                                        echo "<h4>" . $j++ . ") - (___) " . $tx_alternativa_questao . "</h4>";
                                        echo "<h5>Justificativa: " . $tx_justificativa . "</h5>";
                                    }
                                }
                                echo "<br/>";
                                echo "</div>";
                            } ?>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <?php if(!$ocultarBotoes) { ?>
                    <button type="submit" class="btn btn-primary">Imprimir Prova</button>
                    <a href="<?= $this->url('navegacao', ['controller' => $controller, 'action' => 'imprimir-gabarito-pdf', 'id' => Estrutura\Helpers\Cript::enc($dadosProva->getId())]) ?>"
                       class="btn btn-default">Imprimir Gabarito</a>
                <?php } ?>
                <a href="<?= $this->url('navegacao', ['controller' => $controller]) ?>" class="btn btn-default">Voltar</a>
            </div>
        </div>
    </div>
    <?= $this->form()->closeTag(); ?>
</div>
<div class="carregando"><p><img src="/assets/img/carregando1.gif">

    <p></div>

<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        $('.carregando').hide();

        $("#dt_aplicacao_prova").datepicker(
            {dateFormat: 'dd/mm/yy'}
        );

        $("*[name='btnremoverquest']").click(function () {
            $('.carregando').show();
            var questao = $(this).val();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '/prova-prova/remover-questao-prova-ajax',
                async: true,
                data: {
                    id_questao: $(this).val(),
                    id_prova: <?=$dadosProva->getId()?>
                },
                success: function (response) {
                    if (response.sucesso == true) {
                        $('#quest_' + questao).remove();
                        $('.carregando').hide();
                    }
                    $('.carregando').hide();
                }
            });
            //Cancelar o submit do formulario.
            return false;
        });

    });
</script>