<style>
    html, body {
        height: 100%;
        min-height: 100%;
    }

    body {
        font: 15px arial;
        color: rgba(0, 0, 0, .7);
        /*padding: ;*/
    }

    .conteudo {
        margin-left: auto;
        margin-right: auto;
        padding-left: 20px;
        padding-right: 20px;
        text-align: justify;
        font-size: medium;
    }

    table {
        background-color: transparent;
        max-width: 100%;
    }

    .table {
        margin-bottom: 10px;
        width: 100%;
    }

    .tablex {
        line-height: 1.42857;
        padding: 10px;
        padding-top: 30px;
        vertical-align: top;
    }
    .bloco_pai {
        width:100%;
        position: relative;
    }

    .bloco_filho_centralizado {
        margin: 0 auto;
        width: 50%;
    }

    .bloco_filho_direita {
        position: absolute;
        right: 0px;
        top: 0px;
    }

    .bloco_filho_esquerda {
        position: absolute;
        left: 0px;
        top: 0px;
    }

    span.info{
        font-size: 12px;
        padding-left: 10px;
    }
</style>
<div class="bloco_pai">
    <div class="bloco_filho_esquerda">
        <img src="../../../../../public/assets/img/logo/logo-menu2.png" width="160" height="60" />
    </div>
    <div class="bloco_filho_direita">
        <img src="../../../../../public/assets/img/logo/logo-menu.png" width="160" height="60" />

    </div>
</div>
<br>
<br>
<div class="content">

    <?php
    //Objetos criados para Recuperar o nomes pelo ID
    ##
    $areaMateriaService = new \Materia\Service\MateriaService();
    $obj_materia = $areaMateriaService->buscar($dadosProva->getIdMateria());
    ##
    #xd($dadosProva);
    //    $areaClassificacaoSemestreService = new \ClassificacaoSemestre\Service\ClassificacaoSemestreService();
    //    $obj_classificacaoSemestre = $areaClassificacaoSemestreService->buscar($dadosProva->getIdClassificacaoSemestre());

    ?>

    <table class="table tablex" border = "1" cellspacing="0" cellpadding="2" style="font-weight: 900;">
        <tr>
            <td width="60%">
                Nome:
            </td>
            <td width="40%">
                Matrícula:
            </td>
        </tr>
        <tr>
            <td>
                Disciplina: <?= $obj_materia->getNmMateria() ?>
            </td>
            <td>
                Data:
            </td>
        </tr>
        <tr>
            <td>
                Curso: Direito
            </td>
            <td>
                Turma:
            </td>
        </tr>
        <tr>
            <td>
                Professor:
            </td>
            <td>
                Nota:
            </td>
        </tr>
    </table>
</div>
<span class="info">
    <b>Orientações gerais:</b><br>
- Leia atentamente toda a prova;<br>
- Verifique o tempo de duração com o professor;<br>
- Utilize apenas caneta azul ou preta;<br>
- A prova é individual e sem consulta;<br>
- Não será considerada questão objetiva que estiver rasurada;<br>
- Saída permitida após 30 minutos do início de provas<br>
</span>

<div class="conteudo">
    <?php
    $nrQuestoes = count($arQuestoesProva);
    if ($nrQuestoes == 0) { ?>
        <div style="text-align: left" class="row form-group">
            <div class="col-md-12">
                <?php
                echo "<h2> Nao existem questoes adicionadas a esta avaliação</h2>";
                ?>
            </div>
        </div>
        <?php
    } else {
        echo "<h2 style='text-align: center'> Questoes da Prova </h2>";
        ?>
        <div style="text-align: left" class="row form-group">
            <div class="col-md-12">
                <?php
                $questaoService = new \Questao\Service\QuestaoService();
                $alternativaquestaoService = new \AlternativaQuestao\Service\AlternativaQuestaoService();
                $i = 1;
                foreach ($arQuestoesProva as $key => $item) {
                    $arQuestao = $questaoService->buscar($item['id_questao'])->toArray();
                    echo "<h4>" . $i++ . " - " . $arQuestao['nm_titulo_questao'] . "</h4>";
                    echo "<p>" . str_replace("/assets/kcfinder/upload/images/","../../../../../public/assets/kcfinder/upload/images/",$arQuestao['tx_enunciado']) . "</p>";
                    $arAlternativaQuestao = $alternativaquestaoService->fetchAllById(['id_questao' => $item['id_questao']]);
                    $j = 'a';
                    foreach ($arAlternativaQuestao as $key => $alternativa) {
                        echo "<p>" . $j++ . ") " . str_replace("/assets/kcfinder/upload/images/","../../../../../public/assets/kcfinder/upload/images/",$alternativa['tx_alternativa_questao'] ). "</p>";
                    }
                    echo "<br/>";
                } ?>
            </div>
        </div>
        <?php
    }
    ?>
</div>

<?=  $dadosProva->getDsProva() ?>

