<html>
<head>
<!--        <link rel="stylesheet" href="../../../../../public/assets/css/bootstrap.css">-->
    <meta charset=utf-8"/>
    <title>Layout de Impressão</title>

    <style type="text/css">
        @page {
            margin: 120px 50px 80px 50px;
        }

        #topo {
            background-repeat: no-repeat;
            font-size: 25px;
            text-align: center;
            height: 50px;
            width: 100%;
            position: fixed;
            top: -80px;
            left: 0;
            right: 0;
            margin: auto;
            border-bottom: 1px solid #2e2e2e;
        }

        .topo_esquerda {
            position: absolute;
            left: 0px;
            top: 0px;
        }

        .topo_direita {
            position: absolute;
            right: 0px;
            top: 0px;
            font-family: Arial;

        }

        #corpo {
            width: 700px;
            position: relative;
            margin: auto;
            top: -25px;
            text-align: justify;
            font-size: 10px;
            font-family: Arial;
            float: right;
        }

        /*@media screen and (min-width: 480px) {*/
        @media print, dompdf {
            #corpo {
                -webkit-column-count: 2; /* Chrome, Safari, Opera */
                -moz-column-count: 2; /* Firefox */
                column-count: 2;
            }
        }

        #rodape {
            position: fixed;
            bottom: -10px;
            width: 100%;
            text-align: right;
            border-top: 1px solid #2e2e2e;
        }

        #rodape .page:after {
            content: counter(page);
        }

        .rodape_esquerda {
            position: absolute;
            left: 0px;
            top: 0px;
        }

        .rodape_direita {
            position: absolute;
            right: 0px;
            top: 0px;
        }
        .questao {
            background: #000000;
            color: white;
            width: 9%;
            height: 1.3%;
            text-align: center;
        }

    </style>
</head>
<body>
<!--NÃO ALTERAR A ESTRUTURA DO CÓDIGO - MANTER COMO TOPO / RODAPÉ / CORPO-->
<!--informações do cabeçalho-->
<div id="topo" class="text-center">
    <div class="topo_esquerda">
        <img src="../../../../../public/assets/img/logo/logo-faculdade.png" width="160" height="45">
    </div>
    <div class="topo_direita">


        <?php

        #xd($dadosProva);
        $questoesprovaService = new \QuestoesProva\Service\QuestoesProvaService();
        $questoesprovaService->setIdProva($dadosProva->getId());
        #xd($questoesprovaService);
        $nm_prova = '';

        if ($questoesprovaService) {
            $provaService = new \Prova\Service\ProvaService();
            $obProvaEntity = $provaService->buscar($questoesprovaService->getIdProva());
            $nm_prova = $obProvaEntity->getNmProva();
            echo "$nm_prova";
        }
        ?>

        <!--        <img src="../../../../../public/assets/img/logo/logo-menu.png" width="160" height="45">-->
    </div>
</div>
<!--informações do rodapé-->
<div id="rodape" style="font-size: 8px; font-family: Calibri; font-weight: bold">
    <div class="rodape_esquerda">
        <span class="esquerda">Prova Institucional 2º Semestre de 2016</span>
    </div>
    <div class="rodape_direita">
        <span class="direita">Núcleo da Prova Institucional - NPI</span>
    </div>
    <br/>
    <div class="page" align="center">

    </div>
</div>
<!--informações do corpo onde será será impresso as questões-->
<div id="corpo">
    <?php
    $nrQuestoes = count($arQuestoesProva);
    if ($nrQuestoes == 0) { ?>
        <div style="text-align: left" class="row form-group">
            <div class="col-md-12">
                <?php
                echo "<h2> Nao existem questoes adicionadas a esta avaliação</h2>";
                ?>
            </div>
        </div>
        <?php
    } else {
        ?>
            <div>
                <?php
                $questaoService = new \Questao\Service\QuestaoService();
                $alternativaquestaoService = new \AlternativaQuestao\Service\AlternativaQuestaoService();
                $i = 1;
                foreach ($arQuestoesProva as $key => $item) {
                    $arQuestao = $questaoService->buscar($item['id_questao'])->toArray();
                    echo "<h4 class='questao'> QUESTÃO". " ".$i++. "</h4>";
                    echo "<p>" . $arQuestao['tx_enunciado'] . "</p>";
                    $arAlternativaQuestao = $alternativaquestaoService->fetchAllById(['id_questao' => $item['id_questao']]);
                    $j = 'a';
                    foreach ($arAlternativaQuestao as $key => $alternativa) {
                        echo "<span>" . $j++ . ") " . $alternativa['tx_alternativa_questao'] . "</span><br/>";
                    }
                    echo "<br/>";
                } ?>
            </div>

        <?php
    }
    ?>
</div>
<?= $dadosProva->getDsProva() ?>
</body>

</html>