<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">


<div class="col-md-12">
    <div class="table-responsive">
        <table class="table table-striped" id="tablesorterProvas">
            <thead>
            <tr>
                <th class="text-center" style="width: 25%">Nome da prova</th>
                <th class="text-center" style="width: 20%">Aplicação da prova</th>
                <th class="text-center" style="width: 65%">Descrição da prova</th>
                <th class="text-center" colspan="5">Ações</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <th class="text-center" style="width: 25%">Nome da prova</th>
                <th class="text-center" style="width: 20%">Aplicação da prova</th>
                <th class="text-center" style="width: 65%">Descrição da prova</th>
                <th class="text-center" colspan="5">Ações</th>
            </tr>
            <tr>
                <th colspan="8" class="ts-pager form-horizontal">
                    <?php
                    echo $this->paginationControl(
                        $paginator, 'Sliding', 'partials/pagination.phtml', [
                            'urlPagination' => '/prova-prova/index-pagination',
                            'countPerPage' => $countPerPage,
                            'divData' => '#prova-pagination',
                        ]
                    );
                    ?>
                </th>
            </tr>
            </tfoot>
            <?php
            $numeroLinha = (($paginator->getCurrentPageNumber() - 1) * $paginator->getItemCountPerPage());
            if (!empty($paginator)) {
                ?>
                <tbody class="">
                <tr role="row" class="tablesorter-filter-row">
                    <?php
                    foreach ($camposFilter as $key => $campoFilter) {
                        ?>

                        <?php
                        if (!is_null($campoFilter)) {
                            ?>
                            <td>
                                <input type="search" placeholder="" class="tablesorter-filter" data-column="<?= $key ?>"
                                       value="<?= isset($filter[$key]) ? $filter[$key] : '' ?>">
                            </td>
                            <?php
                        } else {
                            ?>
                            <td colspan="5">
                                &nbsp;
                            </td>
                            <?php
                        }
                        ?>

                        <?php
                    }
                    ?>
                </tr>
                <?php
                foreach ($paginator as $key => $prova) { #x($prova['id_prova']);
                    ?>
                    <tr>
                        <td class="text-center"><?= $prova['nm_prova'] ?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\Data::converterDataHoraBancoMySQL2DataBrazil($prova['dt_aplicacao_prova']) ?></td>
                        <td class="text-center"><?= $prova['ds_prova'] ?></td>

                        <td class="text-center">
                            <?= \Estrutura\Service\HtmlHelper::botaoAcao(
                                $this->url('navegacao', array('controller' => $controller, 'action' => 'imprimir-prova-pdf', 'id' => Estrutura\Helpers\Cript::enc($prova['id_prova']))),
                                'Gerar PDF',
                                'gerar_pdf_da_prova',
                                'glyphicon glyphicon-print',
                                'btn-alterar btn-xs btn-alterar-customizado'
                            ) ?>
                        </td>
                        <td class="text-center">
                            <?= \Estrutura\Service\HtmlHelper::botaoAcao(
                                $this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro-questao', 'id' => Estrutura\Helpers\Cript::enc($prova['id_prova']))),
                                'Visualizar Prova',
                                'visualizar_prova',
                                'glyphicon glyphicon-eye-open',
                                'btn-alterar btn-xs btn-alterar-customizado'
                            ) ?>
                        </td>
                        <td class="text-center">
                            <?= \Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro', 'id' => Estrutura\Helpers\Cript::enc($prova['id_prova'])))) ?>
                        </td>
                        <td class="text-center">
                            <?= \Estrutura\Service\HtmlHelper::botaoExcluirConfirm(Estrutura\Helpers\Cript::enc($prova['id_prova'])) ?>
                        </td>
                        <td class="text-center">
                            <?php
                            if ($prova['bo_prova_definitiva'] != true) {
                            ?>
                            <button rel = "<?= $this->url('navegacao', array('controller' => $controller, 'action' => 'marcar-avaliacao-como-aplicada', 'id' => Estrutura\Helpers\Cript::enc($prova['id_prova']))) ?>"
                                    class="btn btn-icon waves-effect waves-light btn-primary m-b-5 btnMarcarAvaliacaoAplicada">
                                <i class="glyphicon glyphicon-thumbs-up"></i>
                            </button>
                            <?php
                            } else {
                            ?>
                                <span class="label label-success">Definitiva</span>
                            <?php
                            }
                            ?>
                        </td>
                    </tr>
                    <?php
                }
                ?>
                </tbody>
                <?php
            }
            ?>
        </table>
        <div class="row">
            <div class="col-md-12">
                <a href="<?= $this->url('navegacao', ['controller' => 'principal-principal']) ?>"
                   class="btn btn-primary" tit le="Retorna para a Página Principal">Home</a>
            </div>
        </div>
    </div>
</div>

<div id="modal-marcar-avaliacao" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">Marcar a prova como aplicada???</h4>
            </div>
            <div class="modal-body">
                Deseja realmente marcar a prova como aplicada???<br><br>
                <br>Observação: <b>Esta ação aplicará o temporizador em todas as questões cadastradas nesta avaliação.</b>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default waves-effect" data-dismiss="modal"><i
                            class="md md-undo"></i> Voltar
                </button>
                <button id="btn-marcar-avaliacao-modal" type="button" class="btn btn-danger waves-effect waves-light" data-dismiss="modal"><i
                            class="md md-delete"></i> Aplicar
                </button>

            </div>
        </div>
    </div>
</div>

<script src="/assets/compact-js/moment.js,validator.min.js,jquery.mask.min.js,jquery.ui.widget.js,jquery.tablesorter.js,jquery.tablesorter.widgets.js,jquery.tablesorter.pager.js"
        type="text/javascript"></script>
<script type="text/javascript" language="javascript">
    $(function () {

        // NOTE: $.tablesorter.theme.bootstrap is ALREADY INCLUDED in the jquery.tablesorter.widgets.js
        // file; it is included here to show how you can modify the default classes
        $.tablesorter.themes.bootstrap = {
            // these classes are added to the table. To see other table classes available,
            // look here: http://getbootstrap.com/css/#tables
            table: 'table table-bordered',
            caption: 'caption',
            header: 'bootstrap-header', // give the header a gradient background
            footerRow: '',
            footerCells: '',
            icons: '', // add "icon-white" to make them white; this icon class is added to the <i> in the header
            sortNone: 'bootstrap-icon-unsorted',
            sortAsc: 'icon-chevron-up glyphicon glyphicon-chevron-up', // includes classes for Bootstrap v2 & v3
            sortDesc: 'icon-chevron-down glyphicon glyphicon-chevron-down', // includes classes for Bootstrap v2 & v3
            active: '', // applied when column is sorted
            hover: '', // use custom css here - bootstrap class may not override it
            filterRow: '', // filter row class
            even: '', // odd row zebra striping
            odd: ''  // even row zebra striping
        };

        // call the tablesorter plugin and apply the uitheme widget
        $("#tablesorterProvas").tablesorter({
            // this will apply the bootstrap theme if "uitheme" widget is included
            // the widgetOptions.uitheme is no longer required to be set
            theme: "bootstrap",
            widthFixed: true,
            headerTemplate: '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!

            // widget code contained in the jquery.tablesorter.widgets.js file
            // use the zebra stripe widget if you plan on hiding any rows (filter widget)
            widgets: ["uitheme", "zebra"],
            widgetOptions: {
                // using the default zebra striping class name, so it actually isn't included in the theme variable above
                // this is ONLY needed for bootstrap theming if you are using the filter widget, because rows are hidden
                zebra: ["even", "odd"],
                // reset filters button
                filter_reset: ".reset"

                // set the uitheme widget to use the bootstrap theme class names
                // this is no longer required, if theme is set
                // ,uitheme : "bootstrap"

            },
            headers: {
                5: {sorter: false}
            }
        });

        $('.prova-acoes-group .btn-excluir').off('click').on('click', function () {

            var id = $(this).attr('rel');
            $("#modal-prova-excluir-id").val(id);
            $('#modal-prova-excluir').modal('show');
        });

        $('#btn-prova-excluir-confirm').off('click').on('click', function () {

            $('#modal-prova-excluir').modal('hide');
            var id = $("#modal-prova-excluir-id").val();
            window.location.href = '/prova-prova/excluirLog/' + id;
        });

        /*Modal de Marcar a avaliação como sendo definitiva*/
        $(".btnMarcarAvaliacaoAplicada").click(function(){
            $(this).attr("data-toggle","modal").attr("data-target","#modal-marcar-avaliacao");
            var rel = $(this).attr('rel');
            $("#btn-marcar-avaliacao-modal").click(function(){
                window.location.href = rel;
            });

        });

    });
</script>