<?php
/** @var $form \Questao\Form\Questao */ //Alysson
/** @var $lista \Questao\Service\Questao[] */ //Alysson

//$id_controller =  $form->get('id_controller')->getValue(); //Alysson
?>
<div class="page-head">
    <h2>Cadastro de Questões</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar')));
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('data-role', 'form');
            $form->prepare();
            echo $this->form()->openTag($form);
            $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
            $id_assunto_materia = $form->get('id_assunto_materia')->getValue();
           #xd($id_assunto_materia);
            echo $this->formHidden($form->get('id'));

            $assunto_materiaService = new \AssuntoMateria\Service\AssuntoMateriaService();
            if (!empty($id_assunto_materia)) {
                $ob_assunto_materia = $assunto_materiaService->buscar($id_assunto_materia);
                $form->get('id_materia')->setValue($ob_assunto_materia->getIdMateria());
            }

            #O Tipo 1 e a questao de multipla eescolha
            $form->get('id_tipo_questao')->setValue(1);
            echo $this->formHidden($form->get('id_tipo_questao'));

            #Temporizador 1 e o de 5 meses
            $form->get('id_temporizacao')->setValue(1);
            echo $this->formHidden($form->get('id_temporizacao'));

            #Preenche o Nivel de Dificuldade como Nao informdo
            $form->get('id_nivel_dificuldade')->setValue(1);
            echo $this->formHidden($form->get('id_nivel_dificuldade'));

            #Seleciona o Projeçao com Fonte padrao da Questao
            $form->get('id_fonte_questao')->setValue(1);
            echo $this->formHidden($form->get('id_fonte_questao'));

            ?>
            <div class="form-group">
                <div class="col-md-6">-
                    <?= $this->formRow($form->get('id_fonte_questao')) ?>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="col-md-6">-
                    <?= $this->formRow($form->get('id_nivel_dificuldade')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-4">-
                    <?= $this->formRow($form->get('id_classificacao_semestre')) ?>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="col-md-4">-
                    <?= $this->formRow($form->get('id_materia')) ?>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="col-md-4">-
                    <?= $this->formRow($form->get('id_assunto_materia')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">-
                    <?= $this->formRow($form->get('nm_titulo_questao')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">-
                    <?= $this->formRow($form->get('tx_enunciado')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <br/>
                    <a href="<?= $this->url('navegacao', ['controller' => $controller]) ?>"
                       class="btn btn-default">Voltar</a>
                    <button type="submit" class="btn btn-primary">Alternativas da Questão</button>
                </div>
            </div>

        </div>
        <br/>

        <div class="row" id=""></div>
    </div>
    <div class="carregando"><p><img src="/assets/img/carregando1.gif"><p></div>
    <script type="text/javascript" language="javascript" class="init">
        $(document).ready(function () {
            $('.carregando').hide();
            $('#id_classificacao_semestre').change(function () {
                if ($(this).val()) {
                    $('#id_materia').hide();
                    $('.carregando').show();
                    $.ajax({
                        type: 'POST',
                        dataType: 'json',
                        url: '/questao-questao/carregar-combo-materias-ajax',
                        async: true,
                        data: {
                            id_classificacao_semestre: $(this).val(),
                        },
                        success: function (response) {
                            if (response.sucesso == true) {
                                var options = '<option value=""> Selecione...</option>';
                                $.each(response.ar_materias, function (i, item) {
                                    options += '<option value="' + response.ar_materias[i].id + '">' + response.ar_materias[i].descricao + '</option>';
                                });
                                $('#id_materia').html(options).show();
                                $('#id_assunto_materia').html('<option value="">-- Escolha uma Matéria --</option>');
                                $('.carregando').hide();
                            } else {
                                $('#id_materia').html('<option value="">-- Erro ao carregar matérias --</option>');

                            }
                        }
                    });
                } else {
                    $('#id_materia').html('<option value="">-- Escolha uma Classificação --</option>');
                    $('#id_assunto_materia').html('<option value="">-- Escolha uma Matéria --</option>');
                }
            });

                $('#id_materia').change(function () {
                    if ($(this).val()) {
                        $('#id_assunto_materia').hide();
                        $('.carregando').show();
                        $.ajax({
                            type: 'POST',
                            dataType: 'json',
                            url: '/questao-questao/carregar-combo-assunto-materia-ajax',
                            async: true,
                            data: {
                                id_materia: $(this).val(),
                            },
                            success: function (response) {
                                if (response.sucesso == true) {
                                    var options = '<option value=""> Selecione...</option>';
                                    $.each(response.ar_assunto_materia, function (i, item) {
                                        options += '<option value="' + response.ar_assunto_materia[i].id + '">' + response.ar_assunto_materia[i].descricao + '</option>';
                                    });
                                    $('#id_assunto_materia').html(options).show();
                                    $('.carregando').hide();
                                } else {
                                    $('#id_assunto_materia').html('<option value="">-- Erro ao carregar Assuntos --</option>');
                                }
                            }
                        });
                    } else {
                        $('#id_assunto_materia').html('<option value="">-- Escolha uma Matéria --</option>');
                    }
                });

            });

    </script>