<?php
/** @var $form \CadastroQuestao\Form\CadastroQuestao */ //Alysson
/** @var $lista \CadastroQuestao\Service\CadastroQuestao[] */ //Alysson

//$id_controller =  $form->get('id_controller')->getValue(); //Alysson
?>
<div class="page-head">
    <h2>Cadastro de Questões</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller'=>$controller,'action' => 'gravar')));
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('data-role', 'form');
            $form->prepare();
            echo $this->form()->openTag($form);
            $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
            //echo $this->formRow($form->get('id_perfil'));
            //echo $this->formRow($form->get('id_controller'));
            ?>
            <div class="form-group">
                <div class="col-md-4">-
                    <?=$this->formRow($form->get('id_fonte_questao'))?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-4">-
                    <?=$this->formRow($form->get('id_classificacao_semestre'))?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-4">-
                    <?=$this->formRow($form->get('id_nivel_dificuldade'))?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4">-
                    <?=$this->formRow($form->get('id_temporizacao'))?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-4">-
                    <?=$this->formRow($form->get('id_tipo_questao'))?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-4">-
                    <?=$this->formRow($form->get('id_assunto_materia'))?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-7">-
                    <?=$this->formRow($form->get('tx_enunciado'))?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-7 ">-
                    <?=$this->formRow($form->get('tx_caminho_imagem_questao'))?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <br /> <button type="submit" class="btn btn-primary">Salvar</button>

                </div>
            </div>



        </div>
        <br />
        <div class="row" id=""></div>
    </div>