<?php
/** @var $form \Questao\Form\Questao */ //Alysson
/** @var $lista \Questao\Service\Questao[] */ //Alysson

//$id_controller =  $form->get('id_controller')->getValue(); //Alysson
?>
<div class="page-head">
    <h2>Cadastro de Questões</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar')));
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('data-role', 'form');
            $form->prepare();
            echo $this->form()->openTag($form);
            $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
            $id_assunto_materia = $form->get('id_assunto_materia')->getValue();
            echo $this->formHidden($form->get('id'));

            $assunto_materiaService = new \AssuntoMateria\Service\AssuntoMateriaService();
            if(!empty($id_assunto_materia)) {
                $ob_assunto_materia = $assunto_materiaService->buscar($id_assunto_materia);
                $form->get('id_materia')->setValue($ob_assunto_materia->getIdMateria());
            }
            ?>
            <div class="form-group">
                <div class="col-md-4">-
                    <?= $this->formRow($form->get('id_classificacao_semestre')) ?>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="col-md-4">-
                    <?= $this->formRow($form->get('id_tipo_questao')) ?>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="col-md-4">-
                    <?= $this->formRow($form->get('id_fonte_questao')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3">-
                    <?= $this->formRow($form->get('id_materia')) ?>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="col-md-3">-
                    <?= $this->formRow($form->get('id_assunto_materia')) ?>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="col-md-3">-
                    <?= $this->formRow($form->get('id_nivel_dificuldade')) ?>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="col-md-3">-
                    <?= $this->formRow($form->get('id_temporizacao')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">-
                    <?= $this->formRow($form->get('nm_titulo_questao')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">-
                    <?= $this->formRow($form->get('tx_enunciado')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <br/>
                    <a href="<?= $this->url('navegacao', ['controller' => $controller]) ?>"
                       class="btn btn-default">Voltar</a>
                    <button type="submit" class="btn btn-primary">Alternativas da Questão</button>
                </div>
            </div>

        </div>
        <br/>

        <div class="row" id=""></div>
    </div>