<div class="page-head">
    <h2>Cadastro de Alternativas</h2>
</div>
<div class="row row-offcanvas row-offcanvas-center">
    <div class="col-xs-12 col-sm-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="light panel-title">Cadastro Questão/Alternativas</h3>
            </div>
            <div class="panel-body" style="background-color: white;">
                <?php
                $form->setAttribute('action', $this->url('navegacao', array('controller' => 'questao-questao', 'action' => 'gravar-alternativas-via-prova')));
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('data-role', 'form');
                $form->setAttribute('method', 'post');
                $form->prepare();
                echo $this->form()->openTag($form);
                $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
                echo $this->formHidden($form->get('id'));

                $assunto_materiaService = new \AssuntoMateria\Service\AssuntoMateriaService();
                $ob_assunto_materia = $assunto_materiaService->buscar($dadosQuestao->getIdAssuntoMateria());

                $form->get('id_questao')->setValue($dadosQuestao->getId());
                echo $this->formHidden($form->get('id_questao'));
                echo "<input type='hidden' id='id_prova' name='id_prova' class='form-control'value='$id_prova'>";

                echo $this->formHidden($form->get('id_alternativa_questao_1'));
                echo $this->formHidden($form->get('id_alternativa_questao_2'));
                echo $this->formHidden($form->get('id_alternativa_questao_3'));
                echo $this->formHidden($form->get('id_alternativa_questao_4'));
                echo $this->formHidden($form->get('id_alternativa_questao_5'));

                $form->get('id_classificacao_semestre')->setValue($dadosQuestao->getIdClassificacaoSemestre());
                $form->get('id_tipo_questao')->setValue($dadosQuestao->getIdTipoQuestao());
                $form->get('id_fonte_questao')->setValue($dadosQuestao->getIdFonteQuestao());
                $form->get('id_materia')->setValue($ob_assunto_materia->getIdMateria());
                $form->get('id_assunto_materia')->setValue($dadosQuestao->getIdAssuntoMateria());
                $form->get('id_nivel_dificuldade')->setValue($dadosQuestao->getIdNivelDificuldade());
                $form->get('id_temporizacao')->setValue($dadosQuestao->getIdTemporizacao());
                $form->get('nm_titulo_questao')->setValue($dadosQuestao->getNmTituloQuestao());
                $form->get('tx_enunciado')->setValue($dadosQuestao->getTxEnunciado());

                if(count($dadosAlternativasQuestao) > 0) {
                    $i = 0;
                    foreach ($dadosAlternativasQuestao as $key => $item) {
                        ++$i;
                        $form->get('id_alternativa_questao_'.$i)->setValue($item['id_alternativa_questao']);
                        $form->get('tx_alternativa_questao_'.$i)->setValue($item['tx_alternativa_questao']);
                        $form->get('cs_correta_'.$i)->setValue($item['cs_correta']);
                        $form->get('tx_justificativa_'.$i)->setValue($item['tx_justificativa']);
                    }
                }
                ?>
                <br/>

                <div class="col-xs-12 col-sm-12">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="light panel-title">Questao</h3>
                        </div>
                        <div class="panel-body" style="background-color: white;">
                            <div class="form-group">
                                <div class="col-md-4">-
                                    <?= $this->formRow($form->get('id_classificacao_semestre')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="col-md-4">-
                                    <?= $this->formRow($form->get('id_tipo_questao')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="col-md-4">-
                                    <?= $this->formRow($form->get('id_fonte_questao')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-3">-
                                    <?= $this->formRow($form->get('id_materia')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="col-md-3">-
                                    <?= $this->formRow($form->get('id_assunto_materia')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="col-md-3">-
                                    <?= $this->formRow($form->get('id_nivel_dificuldade')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="col-md-3">-
                                    <?= $this->formRow($form->get('id_temporizacao')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12">-
                                    <?= $this->formRow($form->get('nm_titulo_questao')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12">-
                                    <?= $this->formRow($form->get('tx_enunciado')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12">
                                <div class="panel panel-info">
                                    <div class="panel-heading">
                                        <h3 class="light panel-title">Alternativa - 1</h3>
                                    </div>
                                    <div class="panel-body" style="background-color: white;">
                                        <!-- Objetivo -->
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_alternativa_questao_1')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('cs_correta_1')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_justificativa_1')) ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12">
                                <div class="panel panel-info">
                                    <div class="panel-heading">
                                        <h3 class="light panel-title">Alternativa - 2</h3>
                                    </div>
                                    <div class="panel-body" style="background-color: white;">
                                        <!-- Objetivo -->
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_alternativa_questao_2')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('cs_correta_2')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_justificativa_2')) ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12">
                                <div class="panel panel-info">
                                    <div class="panel-heading">
                                        <h3 class="light panel-title">Alternativa - 3</h3>
                                    </div>
                                    <div class="panel-body" style="background-color: white;">
                                        <!-- Objetivo -->
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_alternativa_questao_3')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('cs_correta_3')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_justificativa_3')) ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12">
                                <div class="panel panel-info">
                                    <div class="panel-heading">
                                        <h3 class="light panel-title">Alternativa - 4</h3>
                                    </div>
                                    <div class="panel-body" style="background-color: white;">
                                        <!-- Objetivo -->
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_alternativa_questao_4')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('cs_correta_4')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_justificativa_4')) ?>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12">
                                <div class="panel panel-info">
                                    <div class="panel-heading">
                                        <h3 class="light panel-title">Alternativa - 5</h3>
                                    </div>
                                    <div class="panel-body" style="background-color: white;">
                                        <!-- Objetivo -->
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_alternativa_questao_5')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('cs_correta_5')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_justificativa_5')) ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="form-group">
                        <div class="col-md-10">
                            <button type="submit" class="btn btn-primary">Salvar</button>
                            <a href="<?= $this->url('navegacao', ['controller' => 'prova-prova', 'action'=>'cadastro-questao', 'id'=>Estrutura\Helpers\Cript::enc($id_prova)]) ?>" class="btn btn-default">Voltar</a>
                        </div>
                    </div>
                    <?= $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" language="javascript" class="init">
        $(document).ready(function () {


        });
    </script>