<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="/assets/ckeditor/ckedit../../ckeditor.js" type="text/javascript"></script>
<script src="/assets/ckeditor/adapters/jquery.js" type="text/javascript"></script>

<div class="page-head">
    <h2>Cadastro de Alternativas</h2>
</div>
<div class="row row-offcanvas row-offcanvas-center">
    <div class="col-xs-12 col-sm-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="light panel-title">Cadastro Questão/Alternativas</h3>
            </div>
            <div class="panel-body" style="background-color: white;">
                <?php
                #$form->setAttribute('action', $this->url('navegacao', array('controller' => 'questao-questao', 'action' => 'atualizar-dados')));
                $form->setAttribute('action', $this->url('navegacao', array('controller' => 'questao-questao', 'action' => 'atualizar')));
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('data-role', 'form');
                $form->setAttribute('method', 'post');
                 $form->prepare();
                echo $this->form()->openTag($form);
                $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
                echo $this->formHidden($form->get('id'));

                $assunto_materiaService = new \AssuntoMateria\Service\AssuntoMateriaService();
                $ob_assunto_materia = $assunto_materiaService->buscar($dadosQuestao->getIdAssuntoMateria());

                $form->get('id_questao')->setValue($dadosQuestao->getId());
                echo $this->formHidden($form->get('id_questao'));

                echo $this->formHidden($form->get('id_alternativa_questao_1'));
                echo $this->formHidden($form->get('id_alternativa_questao_2'));
                echo $this->formHidden($form->get('id_alternativa_questao_3'));
                echo $this->formHidden($form->get('id_alternativa_questao_4'));
                echo $this->formHidden($form->get('id_alternativa_questao_5'));

                $form->get('id_classificacao_semestre')->setValue($dadosQuestao->getIdClassificacaoSemestre());

                $form->get('id_fonte_questao')->setValue($dadosQuestao->getIdFonteQuestao());
                $form->get('id_materia')->setValue($ob_assunto_materia->getIdMateria());
                $form->get('id_assunto_materia')->setValue($dadosQuestao->getIdAssuntoMateria());
                $form->get('id_nivel_dificuldade')->setValue($dadosQuestao->getIdNivelDificuldade());
                $form->get('id_temporizacao')->setValue($dadosQuestao->getIdTemporizacao());
                $form->get('nm_titulo_questao')->setValue($dadosQuestao->getNmTituloQuestao());
                $form->get('tx_enunciado')->setValue($dadosQuestao->getTxEnunciado());

                if(count($dadosAlternativasQuestao) > 0) {
                    $i = 0;
                    foreach ($dadosAlternativasQuestao as $key => $item) {
                        ++$i;
                        $tx_alternativa_questao = isset($item['tx_alternativa_questao']) && $item['tx_alternativa_questao'] ? $item['tx_alternativa_questao'] : '';
                        $cs_correta = isset($item['cs_correta']) && $item['cs_correta'] ? $item['cs_correta'] : '';
                        $tx_justificativa = isset($item['tx_justificativa']) && $item['tx_justificativa'] ? $item['tx_justificativa'] : '';

                        $form->get('id_alternativa_questao_'.$i)->setValue($item['id_alternativa_questao']);
                        $form->get('tx_alternativa_questao_'.$i)->setValue($tx_alternativa_questao);
                        $form->get('cs_correta_'.$i)->setValue($cs_correta);
                        $form->get('tx_justificativa_'.$i)->setValue($tx_justificativa);
                        
                echo $this->formHidden($form->get('id_alternativa_questao_'.$i));
                
                    }
                }
                ?>
                <br/>

                <div class="col-xs-12 col-sm-12">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="light panel-title">Questao</h3>
                        </div>
                        <div class="panel-body" style="background-color: white;">
                            <div class="form-group">
                                <div class="col-md-4">-
                                    <?= $this->formRow($form->get('id_fonte_questao')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                                
                                <div class="col-md-4">-
                                    <?= $this->formRow($form->get('id_nivel_dificuldade')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="form-group">
                                <div class="col-md-4">-
                                    <?= $this->formRow($form->get('id_temporizacao')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-4">-
                                    <?= $this->formRow($form->get('id_classificacao_semestre')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="col-md-4">-
                                    <?= $this->formRow($form->get('id_materia')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="col-md-4">-
                                    <?= $this->formRow($form->get('id_assunto_materia')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>

                            </div>

                            <div class="form-group">
                                <div class="col-md-12">-
                                    <?= $this->formRow($form->get('nm_titulo_questao')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12">-
                                    <?= $this->formRow($form->get('tx_enunciado')) ?>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            
                            
                            

                            <div class="col-xs-12 col-sm-12">
                                <div class="panel panel-info">
                                    <div class="panel-heading">
                                        <h3 class="light panel-title">Alternativa - 1</h3>
                                    </div>
                                    <div class="panel-body" style="background-color: white;">
                                        <!-- Objetivo -->
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_alternativa_questao_1')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-2">
                                                <?= $this->formRow($form->get('cs_correta_1')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_justificativa_1')) ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12">
                                <div class="panel panel-info">
                                    <div class="panel-heading">
                                        <h3 class="light panel-title">Alternativa - 2</h3>
                                    </div>
                                    <div class="panel-body" style="background-color: white;">
                                        <!-- Objetivo -->
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_alternativa_questao_2')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-2">
                                                <?= $this->formRow($form->get('cs_correta_2')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_justificativa_2')) ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12">
                                <div class="panel panel-info">
                                    <div class="panel-heading">
                                        <h3 class="light panel-title">Alternativa - 3</h3>
                                    </div>
                                    <div class="panel-body" style="background-color: white;">
                                        <!-- Objetivo -->
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_alternativa_questao_3')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('cs_correta_3')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_justificativa_3')) ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12">
                                <div class="panel panel-info">
                                    <div class="panel-heading">
                                        <h3 class="light panel-title">Alternativa - 4</h3>
                                    </div>
                                    <div class="panel-body" style="background-color: white;">
                                        <!-- Objetivo -->
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_alternativa_questao_4')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-2">
                                                <?= $this->formRow($form->get('cs_correta_4')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_justificativa_4')) ?>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12">
                                <div class="panel panel-info">
                                    <div class="panel-heading">
                                        <h3 class="light panel-title">Alternativa - 5</h3>
                                    </div>
                                    <div class="panel-body" style="background-color: white;">
                                        <!-- Objetivo -->
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_alternativa_questao_5')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-2">
                                                <?= $this->formRow($form->get('cs_correta_5')) ?>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <?= $this->formRow($form->get('tx_justificativa_5')) ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
  <script type="text/javascript">
          
                             CKEDITOR.replace('tx_enunciado',
 {
     filebrowserBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=files',
     filebrowserImageBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=images',
     filebrowserUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=files',
     filebrowserImageUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=images'
 });
 
                              CKEDITOR.replace('tx_alternativa_questao_1',
 {
      filebrowserBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=files',
     filebrowserImageBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=images',
     filebrowserUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=files',
     filebrowserImageUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=images'
 });
                             CKEDITOR.replace('tx_alternativa_questao_2',
 {
      filebrowserBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=files',
     filebrowserImageBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=images',
     filebrowserUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=files',
     filebrowserImageUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=images'
 });
                             CKEDITOR.replace('tx_alternativa_questao_3',
 {
     filebrowserBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=files',
     filebrowserImageBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=images',
     filebrowserUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=files',
     filebrowserImageUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=images'
 });
                             CKEDITOR.replace('tx_alternativa_questao_4',
 {
      filebrowserBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=files',
     filebrowserImageBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=images',
     filebrowserUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=files',
     filebrowserImageUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=images'
 });
                             CKEDITOR.replace('tx_alternativa_questao_5',
 {
      filebrowserBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=files',
     filebrowserImageBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=images',
     filebrowserUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=files',
     filebrowserImageUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=images'
 });
 
    $( '#tx_enunciado' ).ckeditor();
            $( '#tx_alternativa_questao_1' ).ckeditor();
            $( '#tx_alternativa_questao_2' ).ckeditor();
            $( '#tx_alternativa_questao_3' ).ckeditor();
            $( '#tx_alternativa_questao_4' ).ckeditor();
            $( '#tx_alternativa_questao_5' ).ckeditor();
                

    </script>
                    </div>
                    <div class="form-group">
                        <div class="col-md-10">
                            <button type="submit" class="btn btn-primary">Salvar</button>
                            <a href="<?= $this->url('navegacao', ['controller' => $controller]) ?>"
                               class="btn btn-default">Voltar</a>
                        </div>
                    </div>
                    <?= $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="carregando"><p><img src="/assets/img/carregando1.gif"><p></div>
    <script type="text/javascript" language="javascript" class="init">
        $(document).ready(function () {
            $('.carregando').hide();
            $('#id_classificacao_semestre').change(function () {
                if ($(this).val()) {
                    $('#id_materia').hide();
                    $('.carregando').show();
                    $.ajax({
                        type: 'POST',
                        dataType: 'json',
                        url: '/questao-questao/carregar-combo-materias-ajax',
                        async: true,
                        data: {
                            id_classificacao_semestre: $(this).val(),
                        },
                        success: function (response) {
                            if (response.sucesso == true) {
                                var options = '<option value=""> Selecione...</option>';
                                $.each(response.ar_materias, function (i, item) {
                                    options += '<option value="' + response.ar_materias[i].id + '">' + response.ar_materias[i].descricao + '</option>';
                                });
                                $('#id_materia').html(options).show();
                                $('#id_assunto_materia').html('<option value="">-- Escolha uma Matéria --</option>');
                                $('.carregando').hide();
                            } else {
                                $('#id_materia').html('<option value="">-- Erro ao carregar matérias --</option>');

                            }
                        }
                    });
                } else {
                    $('#id_materia').html('<option value="">-- Escolha uma Classificação --</option>');
                    $('#id_assunto_materia').html('<option value="">-- Escolha uma Matéria --</option>');
                }
            });

            $('#id_materia').change(function () {
                if ($(this).val()) {
                    $('#id_assunto_materia').hide();
                    $('.carregando').show();
                    $.ajax({
                        type: 'POST',
                        dataType: 'json',
                        url: '/questao-questao/carregar-combo-assunto-materia-ajax',
                        async: true,
                        data: {
                            id_materia: $(this).val(),
                        },
                        success: function (response) {
                            if (response.sucesso == true) {
                                var options = '<option value=""> Selecione...</option>';
                                $.each(response.ar_assunto_materia, function (i, item) {
                                    options += '<option value="' + response.ar_assunto_materia[i].id + '">' + response.ar_assunto_materia[i].descricao + '</option>';
                                });
                                $('#id_assunto_materia').html(options).show();
                                $('.carregando').hide();
                            } else {
                                $('#id_assunto_materia').html('<option value="">-- Erro ao carregar Assuntos --</option>');
                            }
                        }
                    });
                } else {
                    $('#id_assunto_materia').html('<option value="">-- Escolha uma Matéria --</option>');
                }
            });
        });
    </script>