<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="/assets/ckeditor/ckedit../../ckeditor.js" type="text/javascript"></script>
<script src="/assets/ckeditor/adapters/jquery.js" type="text/javascript"></script>


<?php
/** @var $form \Questao\Form\Questao */ //Alysson
/** @var $lista \Questao\Service\Questao[] */ //Alysson

//$id_controller =  $form->get('id_controller')->getValue(); //Alysson
?>
<div class="page-head">
    <h2>Cadastro de Questões</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar-via-prova')));
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('data-role', 'form');
            $form->prepare();
            echo $this->form()->openTag($form);
            $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
            echo $this->formHidden($form->get('id'));
            echo "<input type='hidden' id='id_prova' name='id_prova' class='form-control'value='$id_prova'>";
            $assunto_materiaService = new \AssuntoMateria\Service\AssuntoMateriaService();
            if(!empty($form->get('id_assunto_materia')->getValue())) {
                $ob_assunto_materia = $assunto_materiaService->buscar($form->get('id_assunto_materia')->getValue());
                $form->get('id_materia')->setValue($ob_assunto_materia->getIdMateria());
            }
            ?>
            <div class="form-group">
                <div class="col-md-4">-
                    <?= $this->formRow($form->get('id_classificacao_semestre')) ?>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="col-md-4">-
                    <?= $this->formRow($form->get('id_tipo_questao')) ?>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="col-md-4">-
                    <?= $this->formRow($form->get('id_fonte_questao')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3">-
                    <?= $this->formRow($form->get('id_materia')) ?>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="col-md-3">-
                    <?= $this->formRow($form->get('id_assunto_materia')) ?>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="col-md-3">-
                    <?= $this->formRow($form->get('id_nivel_dificuldade')) ?>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="col-md-3">-
                    <?= $this->formRow($form->get('id_temporizacao')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">-
                    <?= $this->formRow($form->get('nm_titulo_questao')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">-
                    <?= $this->formRow($form->get('tx_enunciado')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <br/>
                    <button type="submit" class="btn btn-primary">Salvar/Editar Alternativas</button>
                    <a href="<?= $this->url('navegacao', ['controller' => 'prova-prova', 'action'=>'cadastro-questao', 'id'=>Estrutura\Helpers\Cript::enc($id_prova)]) ?>" class="btn btn-default">Voltar</a>
                </div>
            </div>

        </div>
        <br/>
        
        <script type="text/javascript">

    CKEDITOR.replace('tx_enunciado',
        {
            filebrowserBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=files',
            filebrowserImageBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=images',
            filebrowserUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=files',
            filebrowserImageUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=images'
        });

    CKEDITOR.replace('tx_alternativa_questao_1',
        {
            filebrowserBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=files',
            filebrowserImageBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=images',
            filebrowserUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=files',
            filebrowserImageUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=images'
        });
    CKEDITOR.replace('tx_alternativa_questao_2',
        {
            filebrowserBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=files',
            filebrowserImageBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=images',
            filebrowserUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=files',
            filebrowserImageUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=images'
        });
    CKEDITOR.replace('tx_alternativa_questao_3',
        {
            filebrowserBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=files',
            filebrowserImageBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=images',
            filebrowserUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=files',
            filebrowserImageUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=images'
        });
    CKEDITOR.replace('tx_alternativa_questao_4',
        {
            filebrowserBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=files',
            filebrowserImageBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=images',
            filebrowserUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=files',
            filebrowserImageUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=images'
        });
    CKEDITOR.replace('tx_alternativa_questao_5',
        {
            filebrowserBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=files',
            filebrowserImageBrowseUrl: '/assets/kcfinder/browse.php?opener=ckeditor&type=images',
            filebrowserUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=files',
            filebrowserImageUploadUrl: '/assets/kcfinder/upload.php?opener=ckeditor&type=images'
        });

    $('#tx_enunciado').ckeditor();
    $('#tx_alternativa_questao_1').ckeditor();
    $('#tx_alternativa_questao_2').ckeditor();
    $('#tx_alternativa_questao_3').ckeditor();
    $('#tx_alternativa_questao_4').ckeditor();
    $('#tx_alternativa_questao_5').ckeditor();


</script>

        

        <div class="row" id=""></div>
    </div>