<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<!--<link rel="stylesheet" href="/assets/css/jquery.tablesorter.theme.bootstrap.css">-->
<!--<link rel="stylesheet" href="/assets/css/jquery.tablesorter.pager.css">-->


<?php
/** @var $form \Questao\Form\Questao */
/** @var $lista \Questao\Service\Questao[] */
?>
<div class="page-head">
    <h2>Questões Cadastradas</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?= $this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro')) ?>" title="Adiciona uma nova Questão">Nova Questão</a>
        </div>
    </div>
    <br />
    <div class="row" id="questao-pagination"></div>
</div>

<div class="modal fade" id="modal-questao-excluir">
    <input type="hidden" name="modal-questao-excluir-id" id="modal-questao-excluir-id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Fechar</span>
                </button>
                <h3 class="modal-title" style="color: #FF0000">ATENÇÃO!!!</h3>
            </div>
            <div class="modal-body alert-danger">
                <span> O item elecionado está prestes de ser excluido definitivamente!!!</span>
                <br/>
                <span> Deseja realmente confirmar a exclusão?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" title="Cancelar">Cancelar</button>
                <button type="button" class="btn btn-danger" id="btn-questao-excluir-confirm" title="Sim"> Sim </button>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/questao-questao/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#questao-pagination').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {

                $('#questao-pagination').html(data);
            }
        });

    })
</script>
