<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<!--<link rel="stylesheet" href="/assets/css/jquery.tablesorter.theme.bootstrap.css">-->
<!--<link rel="stylesheet" href="/assets/css/jquery.tablesorter.pager.css">-->


<?php
/** @var $form \Materia\Form\Materia */
/** @var $lista \Materia\Service\Materia[] */
?>
<div class="page-head">
    <h2>Lista de Matérias</h2><!-- correção - Nathália-->
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?= $this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro')) ?>" title="Adicionar matéria">Nova Matéria</a>
        </div>
    </div>
    <br />
    <div class="row" id="materia-pagination"></div>
</div>

<!--Início do Modal para confirmar a exclusao da Materia-->
<div class="modal fade" id="modal-materia-excluir">
    <input type="hidden" name="modal-materia-excluir-id" id="modal-materia-excluir-id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Fechar</span>
                </button>
                <h3 class="modal-title" style="color: #FF0000">ATENÇÃO!!!</h3>
            </div>
            <div class="modal-body alert-danger">
                <span> A matéria selecionada, está prestes a ser excluída!!!</span>
                <br/>
                <span> Deseja confirmar a exclusão?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" title="Cancelar">Cancelar</button>
                <button type="button" class="btn btn-danger" id="btn-materia-excluir-confirm" title="Sim"> Sim </button>
            </div>
        </div>
    </div>
</div>
<!--Fim do Modal para confirmar a exclusao da Materia-->

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/materia-materia/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#materia-pagination').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {

                $('#materia-pagination').html(data);
            }
        });

    })
</script>
