<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<?php
  /** @var $form \UnidadeTempo\Form\UnidadeTempo */
  /** @var $lista \UnidadeTempo\Service\UnidadeTempo[] */
?>
<div class="page-head">
    <h2>Lista de Unidade de Tempo</h2><!-- correção - Nathália-->
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Adicionar Unidade de Tempo">Nova unidade de tempo</a> <!-- correção - Nathália -->
        </div>
    </div>
    <br />
    <div class="row" id="unidade_tempo-pagination"></div>
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/unidade_tempo-unidadetempo/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#unidade_tempo-pagination').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                        );
            },
            success: function (data) {

                $('#unidade_tempo-pagination').html(data);
            }
        });

    })
</script>
        

