<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<?php
  /** @var $form \Academia\Form\Academia */
  /** @var $lista \Academia\Service\Academia[] */
?>
<div class="page-head">
    <h2>Lista de unidade de tempo</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Adicionar Prova">Novo unidade de tempo</a>
        </div>
    </div>
    <br />
    <div class="row" id="unidade-pagination"></div>    
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/unidade-unidade/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#unidade-pagination').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                        );
            },
            success: function (data) {

                $('#unidade-pagination').html(data);
            }
        });

    })
</script>
        

