
<div class="page-head">
    <h2>Lista de Tipos de Questão</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Adicionar Tipo de Questão">Novo Tipo de Questão</a>
        </div>
    </div>
    <br />
    <div class="row" id="tipoquestao-pagination"></div>
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/tipo_questao-tipoquestao/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#tipoquestao-pagination').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {

                $('#tipoquestao-pagination').html(data);
            }
        });

    })
</script>

