<div>
    <h2>Relatório Usuários</h2>
</div>
<div>
    <table  cellspacing= 15>
        <thead>
            <tr>
                <th>Nome do Usuário</th>
                <th>Perfil </th>
                <th>Função </th>
                <th>Situação </th>
                
            </tr>
        </thead>
        <tbody>
            <?php foreach ($resultado as $linha) { ?>
                <tr>
                    <td><?= $linha['nm_usuario'] ?></td>
                    <td><?= $linha['nm_perfil'] ?></td>
                    <td><?= $linha['nm_funcao'] ?></td>
                    <td><?= $linha['nm_situacao_usuario'] ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>

</div>


