<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<div class="col-md-12">
    <?php
    $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'adicionar-questao-prova-manual')));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id_prova')->setValue($id_prova));
    ?>
    <div class = "table-responsive">
        <table class = "table table-striped" id = "tablesorterDetalhes">
            <thead>
                <tr>
                    <th class = "text-center"></th>
                    <th class = "text-center">Título/Enunciado</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $numeroLinha = (($paginator->getCurrentPageNumber() - 1) * $paginator->getItemCountPerPage());
                if (!empty($paginator)) :
                    foreach ($paginator as $key => $item):
                        ?>
                        <tr>
                            <td class="text-center">
                                <?php echo $this->formElement($form->get($item["id_questao"])); ?>
                            </td>
                            <td>
                                <h4>
                                    <?= ($item['nm_titulo_questao']) ?>
                                </h4>
                                <h5> 
                                    <?= ($item['tx_enunciado']) ?> 
                                </h5>

                                <?php $alternativas = $this->listarAlternativas($item["id_questao"]); ?>
                                <?php $ordemAlternativa = 'a'; ?>
                                <?php foreach ($alternativas as $alternativa) : ?>
                                    <?php if ($alternativa['cs_correta'] == 'C') : ?>
                                        <h4 style='background-color: #4cae4c'>
                                            <?= $ordemAlternativa++ ?> - (_x_) <?= $alternativa['tx_alternativa_questao'] ?>
                                        </h4>
                                        <h5 style='background-color: #4cae4c'>
                                            Justificativa: <?= $alternativa['tx_justificativa'] ?>
                                        </h5>
                                    <?php else: ?>
                                        <h4>
                                            <?= $ordemAlternativa++ ?> - (___) <?= $alternativa['tx_alternativa_questao'] ?>
                                        </h4>
                                        <h5>
                                            Justificativa: <?= $alternativa['tx_justificativa'] ?>
                                        </h5>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="6" class="ts-pager form-horizontal">
                        <?php
                        echo $this->paginationControl(
                                $paginator, 'Sliding', 'partials/pagination.phtml', [
                            'urlPagination' => '/questoes_prova-questoesprova/detalhes-filtros-pagination/' . $id_prova,
                            'countPerPage' => $countPerPage,
                            'divData' => '#detalhesfiltros-pagination',
                                ]
                        );
                        ?>
                    </th>
                </tr>
            </tfoot>
        </table>
    </div>
    <button type="submit" class="btn btn-primary">Adicionar Questões Selecionadas</button>
    <?= $this->form()->closeTag(); ?>
</div>
<!--<script src="/assets/compact-js/moment.js,validator.min.js,jquery.mask.min.js,jquery.ui.widget.js,jquery.tablesorter.js,jquery.tablesorter.widgets.js,jquery.tablesorter.pager.js" type="text/javascript"></script>-->
<script src="/assets/js/moment.js" type="text/javascript"></script>
<script src="/assets/js/validator.min.js" type="text/javascript"></script>
<script src="/assets/js/jquery.mask.min.js" type="text/javascript"></script>
<script src="/assets/js/jquery.ui.widget.js" type="text/javascript"></script>
<script src="/assets/js/jquery.tablesorter.js" type="text/javascript"></script>
<script src="/assets/js/jquery.tablesorter.widgets.js" type="text/javascript"></script>
<script src="/assets/js/jquery.tablesorter.pager.js" type="text/javascript"></script>

<script type="text/javascript" language="javascript">
    $(function () {

        // NOTE: $.tablesorter.theme.bootstrap is ALREADY INCLUDED in the jquery.tablesorter.widgets.js
        // file; it is included here to show how you can modify the default classes
        $.tablesorter.themes.bootstrap = {
            // these classes are added to the table. To see other table classes available,
            // look here: http://getbootstrap.com/css/#tables
            table: 'table table-bordered',
            caption: 'caption',
            header: 'bootstrap-header', // give the header a gradient background
            footerRow: '',
            footerCells: '',
            icons: '', // add "icon-white" to make them white; this icon class is added to the <i> in the header
            sortNone: 'bootstrap-icon-unsorted',
            sortAsc: 'icon-chevron-up glyphicon glyphicon-chevron-up', // includes classes for Bootstrap v2 & v3
            sortDesc: 'icon-chevron-down glyphicon glyphicon-chevron-down', // includes classes for Bootstrap v2 & v3
            active: '', // applied when column is sorted
            hover: '', // use custom css here - bootstrap class may not override it
            filterRow: '', // filter row class
            even: '', // odd row zebra striping
            odd: ''  // even row zebra striping
        };

        // call the tablesorter plugin and apply the uitheme widget
        $("#tablesorterDetalhes").tablesorter({
            // this will apply the bootstrap theme if "uitheme" widget is included
            // the widgetOptions.uitheme is no longer required to be set
            theme: "bootstrap",
            widthFixed: true,
            headerTemplate: '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!

            // widget code contained in the jquery.tablesorter.widgets.js file
            // use the zebra stripe widget if you plan on hiding any rows (filter widget)
            widgets: ["uitheme", "zebra"],
            widgetOptions: {
                // using the default zebra striping class name, so it actually isn't included in the theme variable above
                // this is ONLY needed for bootstrap theming if you are using the filter widget, because rows are hidden
                zebra: ["even", "odd"],
                // reset filters button
                filter_reset: ".reset"

                        // set the uitheme widget to use the bootstrap theme class names
                        // this is no longer required, if theme is set
                        // ,uitheme : "bootstrap"

            },
            headers: {
                5: {sorter: false}
            }
        });

        /*Função Ajax que adiciona os encontros ao Banco de dados*/
        $('#btn-adicionar-questoes-selecionadas').click(function () {
            var dados = $('#questoesprovaform').serialize();
            $.ajax({
                type: "post",
                dataType: "text",
                cache: false,
                url: '/questoes_prova-questoesprova/gravar',
                async: true,
                data: dados,
                success: function (data) {

                }
            });
        });
    });

</script>