
<div class="page-head">
    <h2>Lista de Assuntos</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Adicionar Tema">Novo Assunto</a>
        </div>
    </div>
    <br />
    <div class="row" id="assuntomateria-pagination"></div>
</div>

<!--Início do Modal para confirmar a exclusao da assuntoMateria-->
<div class="modal fade" id="modal-assuntoMateria-excluir">
    <input type="hidden" name="modal-assuntoMateria-excluir-id" id="modal-assuntoMateria-excluir-id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Fechar</span>
                </button>
                <h3 class="modal-title" style="color: #FF0000">ATENÇÃO!!!</h3>
            </div>
            <div class="modal-body alert-danger">
                <span> O assunto selecionado, está prestes a ser excluido!!!</span>
                <br/>
                <span> Deseja confirmar a exclusão?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" title="Cancelar">Cancelar</button>
                <button type="button" class="btn btn-danger" id="btn-assuntoMateria-excluir-confirm" title="Sim"> Sim </button>
            </div>
        </div>
    </div>
</div>
<!--Fim do Modal para confirmar a exclusao da assuntoMateria-->

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/assunto_materia-assuntomateria/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#assuntomateria-pagination').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {

                $('#assuntomateria-pagination').html(data);
            }
        });

    })
</script>

