<?php
/** @var $form \FiltroProva\Form\FiltroProva */
/** @var $lista \FiltroProva\Service\FiltroProva[] */
?>

<!--<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">-->

<div class="page-head">
    <h2>Lista de Filtros de Prova</h2>
</div>

<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Adiconar Filtro de Prova">Novo Filtro de Prova</a>
        </div>
        <br />
        <div class="row" id="filtro_prova-pagination"></div>
    </div>
</div>
<!-- Tabela com os filtros de provas (provisório)
<div class="col-md-12">
    <div class="table-responsive">
        <table class="table table-bordered table-striped" id="tablesorterFiltroProva">
            <thead>
            <tr>
                <th class="text-center">#</th>
                <th class="text-center">Nome do Filtro</th>
                <th class="text-center">Ações</th>
            </tr>
            </thead>

            <tbody>
            <?php foreach($lista as $item){ ?>
                <tr>
                    <td class="text-center">
                        <?=$item->getId()?>
                    </td>
                    <td class="text-center">
                        <?=$item->getNmFiltroProva()?>
                    </td>
                    <td class="text-center">
                        <?=\Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                        <?=\Estrutura\Service\HtmlHelper::botaoExcluir($this->url('navegacao',array('controller'=>$controller,'action'=>'excluir','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                    </td>
                </tr>
            <?php }; ?>
            </tbody>
            <tfoot>
            <tr>
                <th class="text-center">#</th>
                <th class="text-center">Nome do Filtro</th>
                <th class="text-center">Ações</th>
            </tr>
            </tfoot>
        </table>

        <div class="row">
            <div class="col-md-12">
                <a href="<?=$this->url('navegacao', ['controller'=>'principal-principal'])?>" class="btn btn-primary" title="Retorna para a Página Principal">Início</a>
            </div>
        </div>
    </div>
</div>
 -->

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/filtro_prova-filtroprova/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#filtro_prova-pagination').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {
                $('#filtro_prova-pagination').html(data);
            }
        });

    })
</script>