<?php
/** @var $form \FiltroProva\Form\FiltroProva */
/** @var $lista \FiltroProva\Service\FiltroProva[] */
?>

<!--<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">-->

<div class="page-head">
    <h2>Lista de Filtros de Prova</h2>
</div>

<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12"><?php // Botão Novo Filtro?>
            <a class="btn btn-default" href="<?= $this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro')) ?>" title="Adiconar Filtro de Prova">Novo Filtro de Prova</a>
        </div>
    </div>
    <br />
    <div class="row" id="filtroprova-pagination"></div>
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/filtro_prova-filtroprova/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#filtroprova-pagination').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {
                $('#filtroprova-pagination').html(data);
            }
        });

    })
</script>