<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<div class="col-md-12">
    <div class="table-responsive">
        <table class="table table-striped" id="tablesorterDetalhes">
            <thead>
            <tr>
                <th class="text-center">Identificador</th>
                <th class="text-center">Classificação</th>
                <th class="text-center">Matéria</th>
                <th class="text-center">Ações</th>

            </tr>
            </thead>
            <tfoot>
            <tr>
                <th class="text-center">Identificador</th>
                <th class="text-center">Classificação</th>
                <th class="text-center">Matéria</th>
                <th class="text-center">Ações</th>
            </tr>
            <tr>
                <th colspan="6" class="ts-pager form-horizontal">
                    <?php
                    echo $this->paginationControl(
                        $paginator, 'Sliding', 'partials/pagination.phtml', [
                            'urlPagination' => '/materia_semestre-materiasemestre/detalhe-pagination',
                            'countPerPage' => $countPerPage,
                            'divData' => '#materiasemestre-pagination',
                        ]
                    );
                    ?>
                </th>
            </tr>
            </tfoot>
            <?php
            $numeroLinha = (($paginator->getCurrentPageNumber() - 1) * $paginator->getItemCountPerPage());
            if (!empty($paginator)) {
                ?>
                <tbody class="">
                <tr role="row" class="tablesorter-filter-row">
                    <?php
                    foreach ($camposFilter as $key => $campoFilter) {
                        ?>
                        <td>
                            <?php
                            if (!is_null($campoFilter)) {
                                ?>
                                <input type="search" placeholder="" class="tablesorter-filter" data-column="<?= $key ?>"
                                       value="<?= isset($filter[$key]) ? $filter[$key] : '' ?>">
                                <?php
                            } else {
                                ?>
                                &nbsp;
                                <?php
                            }
                            ?>
                        </td>
                        <?php
                    }
                    ?>
                </tr>
                <?php
                foreach ($paginator as $key => $materia_semestre) { #xd($materia_semestre);
                    ?>
                    <tr>
                        <td class="text-center"><?= \Estrutura\Helpers\String::nomeTudoMaiusculo($materia_semestre['id_materia_semestre']) ?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\String::nomeTudoMaiusculo($materia_semestre['nm_classificacao_semestre']) ?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\String::nomeTudoMaiusculo($materia_semestre['nm_materia']) ?></td>
                        <td class="text-center">
                                <span class="btn-group materiaSemestre-acoes-group" style="width: 100px;">
<!--                                 ?= \Estrutura\Service\HtmlHelper::botaoExcluir($this->url(-->
<!--                                         'materia_semestre', array('controller' => 'materia_semestre-materiasemestre', -->
<!--                                     'action' => 'excluir-relacao-materia-semestre', 'id_materia_semestre' => -->
<!--                                         Estrutura\Helpers\Cript::enc($materia_semestre['id_materia_semestre']), -->
<!--                                     'id_classificacao_semestre' => Estrutura\Helpers\Cript::enc($materia_semestre['id_classificacao_semestre']) ))) ?-->

                                  <?= \Estrutura\Service\HtmlHelper::botaoExcluirConfirm(Estrutura\Helpers\Cript::enc($materia_semestre['id_materia_semestre'])) ?>
                                </span>
                        </td>
                    </tr>
                    <?php
                }
                ?>
                </tbody>
                <?php
            }
            ?>

        </table>
        <div class="row">
            <div class="col-md-12">
                <a href="<?= $this->url('navegacao', ['controller' => 'principal-principal']) ?>"
                   class="btn btn-primary" title="Retorna para a Página Principal">Home</a>
                <a class="btn btn-default"
                   href="<?= $this->url('navegacao', array('controller' => $controller, 'action' => 'index')) ?>"
                   title="Lista de Turmas">Lista de Turmas</a>
            </div>
        </div>
    </div>
</div>

<!--Início do Modal para confirmar a exclusao da materiaSemestre-->
<div class="modal fade" id="modal-materiaSemestre-excluir">
    <input type="hidden" name="modal-materiaSemestre-excluir-id" id="modal-materiaSemestre-excluir-id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Fechar</span>
                </button>
                <h3 class="modal-title" style="color: #FF0000">ATENÇÃO!!!</h3>
            </div>
            <div class="modal-body alert-danger">
                <span> A materia por semestre selecionada, está prestes a ser excluída!!!</span>
                <br/>
                <span> Deseja confirmar a exclusão?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" title="Cancelar">Cancelar</button>
                <button type="button" class="btn btn-danger" id="btn-materiaSemestre-excluir-confirm" title="Sim"> Sim </button>
            </div>
        </div>
    </div>
</div>
<!--Fim do Modal para confirmar a exclusao da materiaSemestre-->
<script src="/assets/compact-js/moment.js,validator.min.js,jquery.mask.min.js,jquery.ui.widget.js,jquery.tablesorter.js,jquery.tablesorter.widgets.js,jquery.tablesorter.pager.js" type="text/javascript"></script>
<!--<script src="/assets/js/moment.js" type="text/javascript"></script>-->
<!--<script src="/assets/js/validator.min.js" type="text/javascript"></script>-->
<!--<script src="/assets/js/jquery.mask.min.js" type="text/javascript"></script>-->
<!--<script src="/assets/js/jquery.ui.widget.js" type="text/javascript"></script>-->
<!--<script src="/assets/js/jquery.tablesorter.js" type="text/javascript"></script>-->
<!--<script src="/assets/js/jquery.tablesorter.widgets.js" type="text/javascript"></script>-->
<!--<script src="/assets/js/jquery.tablesorter.pager.js" type="text/javascript"></script>-->

<script type="text/javascript" language="javascript">
    $(function () {

        // NOTE: $.tablesorter.theme.bootstrap is ALREADY INCLUDED in the jquery.tablesorter.widgets.js
        // file; it is included here to show how you can modify the default classes
        $.tablesorter.themes.bootstrap = {
            // these classes are added to the table. To see other table classes available,
            // look here: http://getbootstrap.com/css/#tables
            table: 'table table-bordered',
            caption: 'caption',
            header: 'bootstrap-header', // give the header a gradient background
            footerRow: '',
            footerCells: '',
            icons: '', // add "icon-white" to make them white; this icon class is added to the <i> in the header
            sortNone: 'bootstrap-icon-unsorted',
            sortAsc: 'icon-chevron-up glyphicon glyphicon-chevron-up', // includes classes for Bootstrap v2 & v3
            sortDesc: 'icon-chevron-down glyphicon glyphicon-chevron-down', // includes classes for Bootstrap v2 & v3
            active: '', // applied when column is sorted
            hover: '', // use custom css here - bootstrap class may not override it
            filterRow: '', // filter row class
            even: '', // odd row zebra striping
            odd: ''  // even row zebra striping
        };

        // call the tablesorter plugin and apply the uitheme widget
        $("#tablesorterDetalhes").tablesorter({
            // this will apply the bootstrap theme if "uitheme" widget is included
            // the widgetOptions.uitheme is no longer required to be set
            theme: "bootstrap",
            widthFixed: true,
            headerTemplate: '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!

            // widget code contained in the jquery.tablesorter.widgets.js file
            // use the zebra stripe widget if you plan on hiding any rows (filter widget)
            widgets: ["uitheme", "zebra"],
            widgetOptions: {
                // using the default zebra striping class name, so it actually isn't included in the theme variable above
                // this is ONLY needed for bootstrap theming if you are using the filter widget, because rows are hidden
                zebra: ["even", "odd"],
                // reset filters button
                filter_reset: ".reset"

                // set the uitheme widget to use the bootstrap theme class names
                // this is no longer required, if theme is set
                // ,uitheme : "bootstrap"

            },
            headers: {
                5: {sorter: false}
            }
        });

        $('.materiaSemestre-acoes-group .btn-excluir').off('click').on('click', function () {

            var id = $(this).attr('rel');
            $("#modal-materiaSemestre-excluir-id").val(id);
            $('#modal-materiaSemestre-excluir').modal('show');
        });

        $('#btn-materiaSemestre-excluir-confirm').off('click').on('click', function () {

            $('#modal-materiaSemestre-excluir').modal('hide');
            var id = $("#modal-prova-excluir-id").val();
            window.location.href = '/materia_semestre-materiasemestre/excluir/' + id;
        });

    });
</script>