<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">


<div class="page-head">
    <h2>Lista de Fonte de Questões</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Adicionar Fonte de Questão">Nova Fonte de Questão</a>
        </div>
    </div>
    <br />
    <div class="row" id="fonte-pagination"></div>    
</div>

<!--Início do Modal para confirmar a exclusao da fonte-->
<div class="modal fade" id="modal-fonte-excluir">
    <input type="hidden" name="modal-fonte-excluir-id" id="modal-fonte-excluir-id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Fechar</span>
                </button>
                <h3 class="modal-title" style="color: #FF0000">ATENÇÃO!!!</h3>
            </div>
            <div class="modal-body alert-danger">
                <span> A fonte selecionada, está prestes a ser excluída!!!</span>
                <br/>
                <span> Deseja confirmar a exclusão?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" title="Cancelar">Cancelar</button>
                <button type="button" class="btn btn-danger" id="btn-fonte-excluir-confirm" title="Sim"> Sim </button>
            </div>
        </div>
    </div>
</div>
<!--Fim do Modal para confirmar a exclusao da Prova-->

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/fonte-fonte/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#fonte-pagination').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                        );
            },
            success: function (data) {

                $('#fonte-pagination').html(data);
            }
        });

    })
</script>
        

