<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<?php
  /** @var $form \NivelDificuldade\Form\NivelDificuldade */
  /** @var $lista \NivelDificuldade\Service\NivelDificuldade[] */
?>
<div class="page-head">
    <h2>Lista de Niveis de dificuldade</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Adicionar Prova">Novo Nivel de dificuldade</a>
        </div>
    </div>
    <br />
    <div class="row" id="nivel_dificuldade-pagination"></div>
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/nivel_dificuldade-niveldificuldade/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#nivel_dificuldade-pagination').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                        );
            },
            success: function (data) {
                $('#nivel_dificuldade-pagination').html(data);
            }
        });

    })
</script>
        

